---
title: 'Version control with <i class="fab fa-git"></i> and <i class="fab fa-github"></i> GitHub'
subtitle: 'Using individual repositories on RStudio Cloud'
author: "Kevin Rue-Albrecht"
institute: "Oxford Biomedical Data Science Training Programme"
date: "2022-09-26 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    css: [default, metropolis, rladies-fonts, "my-theme.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

```{r child='layout.Rmd'}
```

---

# Learning Goals & Objectives

### Learning goals

<!--
High-level "big picture" objectives of the learning process.
-->

- Understand what version control is and when to use it.
- Identify where git stores information.
- Practice how to record changes in <i class="fab fa-git"></i>.

### Learning objectives

<!--
More concrete and measurable outputs.
-->

- Set up an SSH key pair.
- Configure <i class="fab fa-git"></i>.
- _Initialise_ a personal repository for this course, on <i class="fab fa-github"></i> GitHub.
- _Clone_ a copy of the repository on the teaching cluster.
- Create and edit files in the repository on the teaching cluster, and _commit_ those changes.
- _Push_ your changes to the <i class="fab fa-github"></i> GitHub clone of the repository.
- Edit files on the <i class="fab fa-github"></i> GitHub clone of the repository.
- _Pull_ updates from the <i class="fab fa-github"></i> GitHub clone to the clone of the repository on the teaching cluster.
- Examine the _log_ of the shared repository, on <i class="fab fa-github"></i> GitHub and on the teaching cluster.

---

# Pre-requisites

- A [<i class="fab fa-github"></i> GitHub](https://github.com/) account.

- Membership to the <i class="fab fa-github"></i> GitHub organisation [OBDS-Training](https://github.com/OBDS-Training).

- An [RStudio Cloud](https://rstudio.cloud/) account.
